AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining

Metrics/MethodLength:
  Max: 12
